name: Deploy to GCP

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute the Commands
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            ls
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
