name: Prettier

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Deps
        run: yarn

      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          commit_message: 'style(global): prettier'
          prettier_options: --write **/*
          only_changed: True
        env:
          GITHUB_TOKEN: ${{ github.token }}
